config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get 'trading', to: 'users#show_trade'
      get 'edit-profile'
      patch 'edit-profile', to: 'users#update'
      get 'change-password', to: 'password_change#new'
      post 'change-password', to: 'password_change#create'
    end
  end
  resources :books, only: [:new, :create, :update, :destroy], path_names: { new: 'search' } do
    collection do
      post 'create', to: 'books#create'
    end

    member do
      patch 'trade/open', to: 'books#open_trading'
      patch 'trade/cancel', to: 'books#cancel_trading'
      patch 'trade/accept', to: 'books#accept_trading'
      delete 'delete', to: 'books#destroy'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  before_save { email.downcase! }
  VALID_USERNAMES = /\A\w+\z/
  validates :username, presence: true, length: { maximum: 30 },
                       format: { with: VALID_USERNAMES },
                       uniqueness: true

  VALID_EMAIL_ADDRESSES = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_ADDRESSES },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :city, length: { maximum: 255 }
  validates :state, length: { maximum: 255 }

  # Return the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user', except: [:new, :create]
  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user, except: [:new, :create]

  def show
    @user = User.find(params[:id])
    @books = @user.books.where(trading: false)
  end

  def show_trade
    @user = User.find(params[:id])
    @books = @user.books.where(trading: true)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit_profile
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit_profile'
    end
  end


  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :city, :state)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_profile_form.html.erb
<div class="board">
  <%= form_for(@user, html: { class: 'profile-form' }) do |f| %>
    <div class="profile-form__group">
      <div class="profile-form__name">
      <%= f.label :username, class: 'profile-form__label' %>
      </div>
      <div class="profile-form__value">
        <%= f.text_field :username, class: 'profile-form__input' %>
      </div>
    </div>
    <div class="profile-form__group">
      <div class="profile-form__name">
      <%= f.label :email, class: 'profile-form__label' %>
      </div>
      <div class="profile-form__value">
        <%= f.text_field :email, class: 'profile-form__input' %>
      </div>
    </div>
    <div class="profile-form__group">
      <div class="profile-form__name">
      <%= f.label :city, class: 'profile-form__label' %>
      </div>
      <div class="profile-form__value">
        <%= f.text_field :city, class: 'profile-form__input' %>
      </div>
    </div>
    <div class="profile-form__group">
      <div class="profile-form__name">
      <%= f.label :state, class: 'profile-form__label' %>
      </div>
      <div class="profile-form__value">
        <%= f.text_field :state, class: 'profile-form__input' %>
      </div>
    </div>
    <div class="profile-form__group">
      <div class="profile-form__name">
      </div>
      <div class="profile-form__value">
        <%= f.submit 'Save changes', class: 'button button--primary' %>
      </div>
    </div>
    <%= render 'shared/error_messages' %>
  <% end %>
</div>

app/views/users/_menu.html.erb
<ul class="menu">
  <li class="menu__item">
    <% if active_menu_link == "Collection" %>
      <i class="fa fa-university"></i>
      <%= link_to 'Collection', @user, class: 'menu__link menu__link--active' %>
    <% else %>
      <i class="fa fa-university"></i>
      <%= link_to 'Collection', @user, class: 'menu__link' %>
    <% end %>
  </li>
  <li class="menu__item">
    <% if active_menu_link == "Trading" %>
      <i class="fa fa-upload"></i>
      <%= link_to 'Trading', trading_user_path(@user), class: 'menu__link menu__link--active' %>
    <% else %>
      <i class="fa fa-upload"></i>
      <%= link_to 'Trading', trading_user_path(@user), class: 'menu__link' %>
    <% end %>
  </li>
  <li class="menu__item">
    <% if active_menu_link == "Edit Profile" %>
      <i class="fa fa-edit"></i>
      <%= link_to 'Edit Profile', edit_profile_user_path(@user), class: 'menu__link menu__link--active' %>
    <% else %>
      <i class="fa fa-edit"></i>
      <%= link_to 'Edit Profile', edit_profile_user_path(@user), class: 'menu__link' %>
    <% end %>
  </li>
  <li class="menu__item">
    <% if active_menu_link == "Change Password" %>
      <i class="fa fa-key"></i>
      <%= link_to 'Change Password', change_password_user_path(@user), class: 'menu__link menu__link--active' %>
    <% else %>
      <i class="fa fa-key"></i>
      <%= link_to 'Change Password', change_password_user_path(@user), class: 'menu__link' %>
    <% end %>
  </li>
  <li class="menu__item">
    <i class="fa fa-sign-out"></i>
    <%= link_to 'Logout', logout_path, method: :delete, class: 'menu__link' %>
  </li>
</ul>

app/views/users/edit_profile.html.erb
<% content_for :sidebar do %>
  <%= render partial: 'menu', locals: { active_menu_link: 'Edit Profile' } %>
<% end %>
<% content_for :detail do %>
  <%= render 'edit_profile_form' %>
<% end %>

app/views/users/new.html.erb
<%= provide(:title, "Sign up for Buuktreid") %>
<main class="main main--alt">
  <div class="main__inner">
    <a class="brand-logo brand-logo--alt-big", href="<%= root_path %>">Buuktreid</a>
    <div class="panel">
      <div class="panel__head">
        <h3 class="h3">Create a new account</h3>
      </div>
      <%= form_for(@user, url: signup_path, html: {class: 'entry-form'}) do |f| %>
        <%= render 'shared/error_messages' %>
        <div class="entry-form__group">
          <%= f.text_field :username, class: 'entry-form__input', placeholder: 'Username' %>
        </div>
        <div class="entry-form__group">
          <%= f.email_field :email, class: 'entry-form__input', placeholder: 'Email address' %>
        </div>
        <div class="entry-form__group">
          <%= f.password_field :password, class: 'entry-form__input', placeholder: 'Password' %>
        </div>
        <div class="panel__note">*All fields are required.</div>
        <%= f.submit 'Sign up', class: 'entry-form__submit button button--primary button--full' %>
      <% end %>
      <div class="panel__foot">Already have an account? <%= link_to 'Login', login_path, class: 'link' %></div>
    </div>
  </div>
</main>
<%= render 'shared/alt_footer' %>

app/views/users/show.html.erb
<% provide(:title, @user.username + " | Buuktreid") %>
<% content_for :sidebar do %>
  <%= render partial: 'menu', locals: { active_menu_link: 'Collection' } %>
<% end %>
<% content_for :detail do %>
  <% if @user.books.any? %>
    <ol class="list">
      <%= render @books %>
    </ol>
  <% end %>
<% end %>

app/views/users/show_trade.html.erb
<% provide(:title, @user.username + " | Buuktreid") %>
<% content_for :sidebar do %>
  <%= render partial: 'menu', locals: { active_menu_link: 'Trading' } %>
<% end %>
<% content_for :detail do %>
  <ol class="list">
    <%= render @books %>
  </ol>
<% end %>