config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get 'trading', to: 'users#show_trade'
      get 'edit-profile'
      patch 'edit-profile', to: 'users#update'
      get 'change-password', to: 'password_change#new'
      post 'change-password', to: 'password_change#create'
    end
  end
  resources :books, only: [:new, :create, :update, :destroy], path_names: { new: 'search' } do
    collection do
      post 'create', to: 'books#create'
    end

    member do
      patch 'trade/open', to: 'books#open_trading'
      patch 'trade/cancel', to: 'books#cancel_trading'
      patch 'trade/accept', to: 'books#accept_trading'
      delete 'delete', to: 'books#destroy'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <div class="user">
      <div class="user__avatar"></div>
      <div class="user__detail">
        <div class="user__name"><%= @user.username %></div>
        <div class="user__email"><%= @user.email %></div>
        <div class="user__books">
          <div class="user__book-count"><%= pluralize(@user.books.count, "book") %></div>
          <%= link_to 'Add books', new_book_path, class: 'button button--small button--secondary' %>
        </div>
      </div>
      </div>
    </div>

    <main class="main">
      <div class="main__inner">
        <div class="dashboard">
          <div class="sidebar">
            <%= yield :sidebar %>
          </div>
          <div class="detail">
            <%= yield :detail %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>